### ISSUE TITLE
Issues with filenames that contain dots

### ISSUE THREAD

**Issue by mf84** [aerleon/pol2yaml#2]
Say you have two policy files, one for in-direction, the other for out direction named like this:

vlan1234.foo.bar.baz-in.pol
vlan1234.foo.bar.baz-out.pol

The converter script will ignore everything behind the first dot and create a new file called:

vlan1234.yaml

The resulting file only contains the in-acl, the out-acl is missing.

Tested with node/18.16.1 and pol2yaml 1.2.0.

**Comment by jtwb** [comment]
Thanks @mf84. I just updated pol2yaml on NPM with the fix. pol2yaml 1.2.1 resolves this issue.

**Comment by jtwb** [comment]
Also feel free to join the Aerleon slack server if you haven't already: https://join.slack.com/t/aerleon/shared_invite/zt-1ngckm6oj-cK7yj63A~JgqjixEui2Vhw
